name: My First Workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout action
          uses: actions/checkout@v5

        - name: Welcome Message
          run: echo "My first job action in Github"

        - name: List Files
          run: ls

        - name: Read File
          run: cat README.md
          


  
