name: Generate ASCII ArtWork
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout action
          uses: actions/checkout@v5

        - name: List all the files in the Repo 
          run: ls -lrat

        - name: Executing Shell Script 
          run: ./ascii-script.sh
