name: Generate ASCII ArtWork
on: push
jobs:
  building_job:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout action
          uses: actions/checkout@v5

        - name: List all the files in the Repo 
          run: ls -lrat

        - name: Executing Shell Script 
          run: |
            sudo apt-get install cowsay
            cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt
        
        - name: Upload static files as artifact
          uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
          with:
            name: dragon_artifact
            path: dragon.txt

  testing_job:
    needs: building_job
    runs-on: ubuntu-latest
    steps:
        - name: Download the artifacts
          uses: actions/download-artifact@v5
          with:     
            name: dragon_artifact
            path: dragon.txt

        - name: Verifies the file is there
          run: grep -i "dragon" ./artifacts/dragon.txt 

  deployment_job:
    needs: testing_job
    runs-on: ubuntu-latest
    steps:

        - name: Download the artifacts
          uses: actions/download-artifact@v5
          with:     
            name: dragon_artifact
            path: dragon.txt

        - name: Reads the file from production
          run: cat ./dragon.txt
      
        - name: Deploying into Production
          run: echo "Deploying into PROD ..."
